---
- name: pre (install dependencies)
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    state: present
    update_cache: yes

- name: add gpg docker key
  apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present

- name: add docker repo
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable"
    state: present
    update_cache: yes

- name: install docker
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: present
    update_cache: yes

- name: start docker
  service:
    name: docker
    state: started
    enabled: yes

- name: install docker compose
  get_url:
    url: https://github.com/docker/compose/releases/download/v2.20.0/docker-compose-linux-x86_64
    dest: /usr/local/bin/docker-compose
    mode: '0755'

- name: check docker compose version
  command: docker-compose --version
  register: docker_compose_version
  changed_when: false

- name: check docker compose version
  debug:
    msg: "{{ docker_compose_version.stdout }}"

- name: add user to docker group
  user:
    name: "{{ docker_user }}"
    groups: docker
    append: yes
