[Interface]
ListenPort = 15604
Address = 192.168.110.1/24
PrivateKey = GBVn9CyJ2Nzi814bZbYGXznJXOiePKPMELyjgv4lsH4=

PostUp = iptables -A FORWARD -i %i -j ACCEPT; iptables -A FORWARD -o %i -j ACCEPT; iptables -t nat -A POSTROUTING -o enp1s0 -j MASQUERADE
PostDown = iptables -D FORWARD -i %i -j ACCEPT; iptables -D FORWARD -o %i -j ACCEPT; iptables -t nat -D POSTROUTING -o enp1s0 -j MASQUERADE

# Client 1 server conf example
[Peer]
PublicKey = NT7sHz1G7RkFg4qRjpKpRaOWatJHCWePzj9H0bEPTnU=
AllowedIPs = 192.168.110.2/32, 10.200.0.0/24

# ============================                                                             
# Client 1 client conf example                                                             
# ============================                                                             
                                                                                           
# [Interface]                                                                              
# Address = 192.168.110.2/32                                                               
# PrivateKey = sFg2eNCKPkDNicUi5+nqaZ27mhrAsKJnPPEI/eXRk14=                                
                                                                                           
# PostUp = iptables -A FORWARD -i wg0 -j ACCEPT; iptables -t nat -A POSTROUTING -o ens160 -j MASQUERADE                                                                               
# PostDown = iptables -D FORWARD -i wg0 -j ACCEPT; iptables -t nat -D POSTROUTING -o ens160 -j MASQUERADE                                                                             
                                                                                           
# [Peer]                                                                                   
# Endpoint = 192.168.122.104:15604                                                         
# PublicKey = p9eC9TeI/I1oTQYMRmz1VZO8Z9qKLlHhvfbRjRBKDHU=                                 
# AllowedIPs = 192.168.110.1/32, 192.168.122.0/24                                          
# PersistentKeepalive = 15   