---
- name: Install fastfetch deb
  hosts: all
  become: yes
  vars:
    arch: "amd64"
  tasks:
    - name: Download fastfetch .deb
      ansible.builtin.get_url:
        url: "https://github.com/fastfetch-cli/fastfetch/releases/download/2.34.1/fastfetch-linux-{{ arch }}.deb"
        dest: "/tmp/fastfetch-linux-{{ arch }}.deb"

    - name: Install fastfetch from .deb
      ansible.builtin.apt:
        deb: "/tmp/fastfetch-linux-{{ arch }}.deb"

    - name: Delete .deb package
      ansible.builtin.file:
        path: "/tmp/fastfetch-linux-{{ arch }}.deb"
        state: absent

    - name: Get list of all users
      ansible.builtin.shell: |
        getent passwd | awk -F: '$3 >= 1000 && $3 < 65534 {print $1}'
      register: all_users
      become: no

    - name: Add fastfetch to each user's .bashrc
      ansible.builtin.lineinfile:
        path: "/home/{{ item }}/.bashrc"
        line: "fastfetch"
        create: yes
        insertafter: EOF
      loop: "{{ all_users.stdout_lines }}"
