---
- name: Update apt cache
  apt:
    update_cache: yes

- name: Install essential packages
  apt:
    name: "{{ packages }}"
    state: present

- name: Create a new user
  user:
    name: "{{ username }}"
    password: "{{ user_password | password_hash('sha512') }}"
    shell: /bin/sh
    groups: sudo
    append: yes

- name: Configure sudo for the user
  copy:
    dest: /etc/sudoers.d/{{ username }}
    content: "{{ username }} ALL=(ALL) NOPASSWD:ALL"
    validate: /usr/sbin/visudo -cf %s

- name: Set sh as the default shell
  command: chsh -s /bin/sh {{ username }}
  when: ansible_user != 'root'

- name: Ensure .ssh directory exists
  file:
    path: /home/{{ username }}/.ssh
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0700

- name: Ensure authorized_keys file exists
  file:
    path: /home/{{ username }}/.ssh/authorized_keys
    state: touch
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0600

- name: Add SSH public key to authorized_keys
  ansible.builtin.authorized_key:
    user: "{{ username }}"
    state: present
    key: "{{ lookup('file', ssh_public_key_path) }}"

- name: Enable UFW firewall
  ufw:
    state: enabled
    policy: deny
    direction: incoming

- name: Allow SSH through UFW
  ufw:
    rule: allow
    name: OpenSSH

- name: Reboot the server (if required)
  reboot:
