---
galaxy_info:
  author: ini
  description: Role for setting up a fresh Debian system
  license: MIT
  min_ansible_version: 2.9
  platforms:
    - name: Debian
      versions:
        - buster
        - bullseye
        - bookworm
